[package]
name = "opencv-camera"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
opencv = { git = "https://github.com/twistedfall/opencv-rust", default-features = false, features = ["opencv-4"] }
standard-vision = { path = "../standard-vision" }

[dev-dependencies]
png = "^0.15.2"
