[package]
name = "opencv-camera"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
opencv = { version = "0.29", default-features = false, features = ["opencv-4"] }
standard-vision = { path = "../standard-vision" }
ndarray = "0.13.0"

[dev-dependencies]
png = "^0.15.2"
