[package]
name = "stdvis-opencv"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
stdvis-core = { path = "../stdvis-core" }
ndarray = "0.13.0"
opencv = "0.62"

[dev-dependencies]
png = "^0.15.2"
