[package]
name = "stdvis-core"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
anyhow = "1.0"
mincodec = { git = "https://github.com/noocene/mincodec" }
ndarray = { version = "0.13", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
